services:
  app :
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8008:8000
    depends_on:
      - db
    volumes:
      - ./keys:/keys
  db:
    build: ./owlappdb/
