services:
  app :
    build: ./owlapp/
    environment:
      # authentication
      GOOGLE_APPLICATION_CREDENTIALS: ${GCP_KEY_PATH}
      volumes:
      # Inject service account key file into the container at runtime:
      - ${GCP_KEY_PATH}:${GCP_KEY_PATH}:ro
  db:
    build: ./owlappdb/
